Docs: Binary & Stream Executions
appwrite/website pull request #1082
Opened 2024-07-01 21:24 UTC by choir27

## What does this PR do?

- [ ] Update Develop > response
    - [ ] Break down different sections for each request/response type
    - [ ] Replace req.bodyRaw with req.bodyText
    - [ ] Don’t use req.body because it may not detect so replace with bodyText or bodyJson depending on expected input
    - [ ] Add deprecation notice for req.bodyRaw and req.bodyText and res.send
    - [ ] Res.send should be res.text

## Test Plan

X

## Related PRs and Issues

X

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-07-17 21:48 UTC, stnguyen90 requested changes

2024-07-17 21:48 UTC, stnguyen90 commented on src/routes/docs/products/functions/develop/+page.markdoc
> +Use `req.bodyText` instead of `req.bodyRaw`. Use `res.text` instead of `res.send`. Use `req.bodyText` or `req.bodyJson` instead of `req.body` depending on the expected input data type.
What's this section about compared to what's in this notice?

2024-07-17 21:48 UTC, stnguyen90 commented on src/routes/docs/products/functions/develop/+page.markdoc
> +    log(JSON.stringify(req.bodyJson));        // Object from parsed JSON request body, otherwise string
Fix the alignment of the comments. Please make sure to address the other code samples too.

2024-07-17 21:48 UTC, stnguyen90 commented on src/routes/docs/products/functions/develop/+page.markdoc
> +
let's focus on the request and response types that correspond to the methods. For example, in node [req](https://github.com/open-runtimes/open-runtimes/blob/b86962c170c4ca043cf1167db9cfc44c9a985292/runtimes/node/versions/latest/src/server.js#L70-L95) and [res](https://github.com/open-runtimes/open-runtimes/blob/b86962c170c4ca043cf1167db9cfc44c9a985292/runtimes/node/versions/latest/src/server.js#L107-L130).

2024-07-19 16:29 UTC, choir27 commented
Closing this PR because the base branch for `docs-binary-and-stream` is `main`, but the base branch should be the `1.6.x`.

2024-07-19 16:29 UTC, closed without merging