docs: Update Appwriter docs
appwrite/website pull request #1096
Opened 2024-07-05 13:25 UTC by choir27

## What does this PR do?

Updates Appwriter docs
- Updates with new link to Appwrite store
- Updates respective to preorder state of Appwriter
 
Fixes #1094 

## Test Plan

X

## Related PRs and Issues

- https://github.com/appwrite/website/issues/1094

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-07-08 10:51 UTC, LauraDuRy commented on src/routes/docs/tooling/appwriter/+page.markdoc
> +The Appwriter is also available from Appwrite events and giveaways.
This sentence feels a bit of. Maybe we can say: "You can also partake in our giveaways and win the Appwriter."

2024-07-08 18:02 UTC, stnguyen90 requested changes

2024-07-08 18:02 UTC, stnguyen90 commented on src/routes/docs/tooling/appwriter/+page.markdoc
> +Look out for events & giveaways on our social media
```suggestion
Look out for events & giveaways on our social media:
```

2024-07-09 08:06 UTC, LauraDuRy approved these changes

2024-07-15 04:37 UTC, stnguyen90 approved these changes

2024-07-15 04:38 UTC, merged