Fix: Display only Open Issues
appwrite/website pull request #1128
Opened 2024-07-16 11:52 UTC by ItzNotABug

## What does this PR do?

Show only Open Issues on Community Page.

## Test Plan

Manual.

## Related PRs and Issues

N/A.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

2024-07-16 12:02 UTC, ItzNotABug commented
@TorstenDittmann should we make the layout of this as well? I see a lot of empty space -

<img width="1192" alt="Screenshot 2024-07-16 at 5 24 22 PM" src="https://github.com/user-attachments/assets/04d2721c-ced3-41d6-83e0-5881d6d47ed0">

Something like this?

<img width="958" alt="Screenshot 2024-07-16 at 5 32 21 PM" src="https://github.com/user-attachments/assets/78b6d97a-bc7e-4c92-acd3-477c2d3758dd">

2024-08-08 13:19 UTC, TorstenDittmann requested changes

2024-08-08 13:19 UTC, TorstenDittmann commented on src/routes/community/+page.server.ts
>      const response = await fetch('https://api.github.com/repos/appwrite/appwrite/issues');
https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues you can use the github api to only return open issues 👍🏻 
<img width="584" alt="Bildschirmfoto 2024-08-08 um 15 19 27" src="https://github.com/user-attachments/assets/f6e95e39-2896-4ede-9dd8-6ef0535c71de">

2024-08-12 07:29 UTC, ItzNotABug commented
@TorstenDittmann what do you think of the layout suggestion?

2024-09-04 13:00 UTC, TorstenDittmann commented on src/routes/community/+page.server.ts
> +
I dont think we need this anymore 👀 since its filtered by the api

2024-11-28 08:09 UTC, ernstmul approved these changes

2024-12-12 13:59 UTC, TorstenDittmann approved these changes

2024-12-12 13:59 UTC, merged