Add Image Classification Blog Post
appwrite/website pull request #1149
Opened 2024-07-23 10:25 UTC by PineappleIOnic

## What does this PR do?

This PR adds the image classification blog post

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-07-23 11:48 UTC, christyjacob4 approved these changes

2024-07-23 11:49 UTC, christyjacob4 commented on src/routes/blog/post/image-classification/+page.markdoc
> +## Architectures
Maybe you can use H1s here?  and for #Datasets and examples

2024-08-06 11:07 UTC, loks0n requested changes

2024-08-06 11:07 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +With the function boilerplate created, we will replace the `main.py` file with a script we'll run on our function to load the model we just trained and make evaluations based on it. Replace all the c
```suggestion
With the function boilerplate created, replace the `main.py` file with a script to load the model we just trained and run inference:
```

2024-08-06 11:07 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +We also want to add a requirements.txt file with TensorFlow and NumPy, so we have all the dependencies we need:
```suggestion
Add a requirements.txt file with TensorFlow and NumPy, to fetch the required dependencies:
```

2024-08-06 11:07 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +Next, move the model.tflite file that was created into the same directory as your main.py file and then change directories to where your appwrite.json is stored. This model.tflite is quite a small fi
```suggestion
Move the `model.tflite` file that was created into the same directory as the `main.py` file and then change directories to that containing the `appwrite.json`. This `model.tflite` is quite a small file, so store it in the function. If using larger models, upload them to Appwrite Storage and then use `getFileDownload` to download them to the function. 
```

2024-08-06 11:07 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +With the file now copied, run appwrite deploy function and select the function you just created to deploy it to Appwrite.
```suggestion
With the file now copied, run appwrite deploy function and select the function to deploy it to Appwrite.
```

2024-08-06 11:07 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +Finally, send a `POST` request to your function with a JSON body that contains a file ID from your bucket like this:
```suggestion
Finally, send a `POST` request to the function with a JSON body that contains a file ID from the bucket like this: 
```

2024-08-06 11:07 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +Finding data to train these architectures can sometimes be the most challenging part of developing state-of-the-art image classification models. It was tough in the early days, but these days, we hav
```suggestion
Finding data to train these architectures used to b the most challenging part of developing state-of-the-art image classification models. Now, however, there is standardized high-quality labeled data that is offered entirely free for any researchers who require it. Next, we'll cover some of the most popular datasets.
```

2024-08-07 14:11 UTC, loks0n approved these changes

2024-08-07 14:13 UTC, loks0n approved these changes
spotted a few titles that should be sentence case.

LGTM otherwise

2024-08-07 14:13 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +Image Classification is an exciting field of Computer Vision that tries to understand and label images in their entirety. It has many applications: you can integrate it into your app to automatically
```suggestion
Image classification is an exciting field of computer vision that tries to understand and label images in their entirety. It has many applications: you can integrate it into your app to automatically categorize photos, filter inappropriate content from social media feeds, or even organize your online store's product catalog.
```

2024-08-07 14:13 UTC, loks0n commented on src/routes/blog/post/image-classification/+page.markdoc
> +# A Brief History of Image Classification
```suggestion
# A brief history of image classification
```

2024-08-13 11:09 UTC, merged