Add 1.6.x references
appwrite/website pull request #1159
Opened 2024-07-26 23:25 UTC by stnguyen90

## What does this PR do?

Update API references to include 1.6.x and set Cloud to point to 1.6.x references.

## Test Plan

Manual:

<img width="1574" alt="image" src="https://github.com/user-attachments/assets/a3c7ef85-1b35-4c17-8762-08740cc3e846">

## Related PRs and Issues

None

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-08-07 18:53 UTC, choir27 requested changes

2024-08-07 18:53 UTC, choir27 commented on pnpm-lock.yaml
Is `pnpm-lock.yaml` supposed to be updated?

2024-08-08 04:11 UTC, stnguyen90 commented on pnpm-lock.yaml
Yes, because package.json was updated.

2024-08-08 13:11 UTC, choir27 approved these changes

2024-08-08 17:15 UTC, merged