Intergrations catalog
appwrite/website pull request #1163
Opened 2024-07-30 07:27 UTC by LauraDuRy

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-07-30 09:36 UTC, SnezhannaM approved these changes

2024-07-31 17:32 UTC, adityaoberai commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +This catalog is designed to empower you by providing a seamless way to integrate your favorite tools, libraries, and services with Appwrite, making your development process even more efficient and en
Would it be better to start this with `Our new Integrations catalog` instead of `This catalog`?

2024-07-31 18:01 UTC, adityaoberai requested changes
@LauraDuRy was just reviewing the blog PRs and these caught my eye

Might be worth a look before we announce

2024-08-01 05:56 UTC, LauraDuRy commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +## Version control
I am not sure what you are referring to, can you adjust it in the text directly?

2024-08-01 05:56 UTC, LauraDuRy commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +- Notion
Please add

2024-08-01 05:56 UTC, LauraDuRy commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +- Algolia for Search
Also not sure what you are referring to here, please adjust directly

2024-08-01 05:57 UTC, adityaoberai commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +- Notion
I'll add a couple of lines

2024-08-01 05:57 UTC, adityaoberai commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +- Algolia for Search
I meant separating Search and Databases 

I can handle that though :)

2024-08-01 05:58 UTC, adityaoberai commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +## Version control
Will do

Context: we renamed the Version control category to Deployments

2024-08-01 05:58 UTC, adityaoberai commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +Monitor your app's performance, trace errors, and fix your app faster. These tools help you proactively manage issues, optimize performance, and deliver a smoother user experience:
I'll edit this

2024-08-01 10:58 UTC, adityaoberai approved these changes

2024-08-01 11:01 UTC, adityaoberai commented on src/routes/blog/post/announcing-appwrite-integration-catalog/+page.markdoc
> +As with everything we do here at Appwrite, we heavily focus on the developer experience. Our main goal with the Integration Catalog is to meet your needs when integrating X with Appwrite. We focussed
```suggestion
As with everything we do here at Appwrite, we heavily focus on the developer experience. Our main goal with the Integration Catalog is to meet your needs when integrating X with Appwrite. We focused on a set of principles that helped us deliver on our promise:
```

2024-08-01 11:12 UTC, merged