docs: update version for go(golang)
appwrite/website pull request #1249
Opened 2024-08-21 15:37 UTC by choir27

## What does this PR do?

Updates go version throughout docs

## Test Plan

X

## Related PRs and Issues

https://github.com/appwrite/website/pull/1147
https://github.com/appwrite/website/pull/1136/files

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-08-21 22:53 UTC, stnguyen90 requested changes

2024-08-21 22:53 UTC, stnguyen90 commented on src/routes/docs/sdks/+page.markdoc
> +* Go SDK `1.23`
These should be the go SDK version rather than go runtime version.

2024-08-22 15:19 UTC, christyjacob4 commented on src/routes/docs/sdks/+page.markdoc
> +* Go SDK `0.0.1`
same here

2024-08-22 15:19 UTC, christyjacob4 requested changes
Please address the comments

2024-08-23 08:37 UTC, Meldiron approved these changes

2024-08-23 15:18 UTC, merged