Document Backups
appwrite/website pull request #1371
Opened 2024-09-23 13:33 UTC by ItzNotABug

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-09-25 08:54 UTC, eldadfux requested changes

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +title: Database Backups
```suggestion
title: Backups
```

I think we can go with the simpler title here.

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +## Create Backups {% #create-backups %}
All of our titles should be sentence case per our writing style guide.

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +# Backups {% #backups %}
This title is repetitive we can skip it.

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +Appwrite Backups enable you to automate database backups using Backup Policies, with support for both pre-defined and custom retention options. You can also create manual backups whenever necessary.
Not just custom retention options. Retention is only one setting in a policy.

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +## Create Backups {% #create-backups %}
This is a section about policies. I would adjust the title, start by explaining what a policy is, and then have another sub-heading with the steps to create a policy. 

The same way we might want to add a section for manual backups.

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +Your database is now set up for automated backups with just a few clicks.\
```suggestion
Your database is now set up for automated backups with just a few clicks.
```

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +   Regularly check the backup status in the Backups Tab to ensure no scheduled backups have failed.
Let's make sure we log errors when a backup fails, this shouldn't really be an option for users. This should be our responsibility to check not the developer's.

2024-09-25 08:54 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +   Critical data may require more frequent backups, while less essential data can have longer retention and fewer backups.
I miss a section where we can provide some important reassurances like the fact all backups are stored in a remote location, and all backups are encrypted.

2024-09-25 08:57 UTC, eldadfux commented on src/routes/docs/products/databases/backups/+page.markdoc
> +{% info title="Backups are an Appwrite Cloud feature and available on the Enterprise plan" %}
```suggestion
{% info title="Backups are available on Appwrite Cloud for all Pro, Scale, and Enterprise customers." %}
```

2024-09-30 15:24 UTC, Herry0092 approved these changes

2024-10-17 11:37 UTC, christyjacob4 approved these changes

2024-10-17 11:37 UTC, merged