Add Database Backups announcement
appwrite/website pull request #1421
Opened 2024-10-10 11:32 UTC by ebenezerdon

## What does this PR do?

- Adds database backups announcement
- Adds entry to changelog
- Add blog post assets
- Fixes syntax error with deno changelog entry

## Test Plan

- Run the website and navigate to `/blog/post/introducing-database-backups`
- Confirm that blog post exists and that the assets are displayed correctly
- Navigate to `/changelog` and confirm that new database backups entry is displayed
- Confirm that deno announcement changelog entry is displayed

## Related PRs and Issues

None

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-10-10 12:14 UTC, LauraDuRy approved these changes

2024-10-10 13:01 UTC, adityaoberai approved these changes

2024-10-15 13:43 UTC, adityaoberai requested changes
@ebenezerdon the dates in the blog and the changelog need to be updated

2024-10-15 15:38 UTC, adityaoberai commented on src/routes/changelog/(entries)/2024-10-15.markdoc
> +date: 2024-10-10
```suggestion
date: 2024-10-15
```

2024-10-15 15:42 UTC, adityaoberai commented on src/routes/+page.svelte
> +
```suggestion
                        <span class="text-caption web-u-trim-1"
                            >Introducing Database Backups</span
                        >
```

2024-10-15 15:54 UTC, merged