Update GitHub Stars Count
appwrite/website pull request #1460
Opened 2024-10-26 23:13 UTC by gurjeetsinghvirdee

## What does this PR do?

This pull request updates the GitHub stars count displayed on the website.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

#1439 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-10-26 23:25 UTC, gurjeetsinghvirdee commented
apologize for the issue. Due to unexpected system lag, I mistakenly deleted a branch and inadvertently closed the associated pull request. However, I have opened the PR again

2024-10-28 15:31 UTC, DH-555 requested changes
It's now 45k 😅

2024-10-28 15:38 UTC, gurjeetsinghvirdee commented
> It's now 45k 😅

Updated

2024-11-01 14:54 UTC, DH-555 approved these changes

2024-11-02 00:22 UTC, stnguyen90 approved these changes

2024-11-02 00:23 UTC, merged