Update backups page to mention our self-managed backups
appwrite/website pull request #1466
Opened 2024-10-29 14:26 UTC by ebenezerdon

## What does this PR do?

Updates the backups page in the docs to mention our self-managed backups.

## Test Plan

- Run the app and navigate to `/docs/advanced/security/backups`
- Confirm that the content and link reference are displayed correctly

2024-10-29 14:35 UTC, tessamero reviewed
change "data bases" to "databases"

2024-10-29 14:41 UTC, tessamero approved these changes

2024-11-01 18:02 UTC, stnguyen90 requested changes

2024-11-01 18:02 UTC, stnguyen90 commented on src/routes/docs/advanced/security/backups/+page.markdoc
> +Appwrite Cloud provides both automated and self-managed backups.
Let's clarify there's:

1. self-managed backups for Appwrite project Databases.
2. backups of the underlying database for disaster recovery.

The order of the topics here should also match the order of the topics below.

2024-11-01 18:02 UTC, stnguyen90 commented on src/routes/docs/advanced/security/backups/+page.markdoc
> +Users can configure automatic backup policies or initiate manual backups directly from the Console.
Let's clarify these self-managed backups are for pro plans and above and link to the backups documentation here.

2024-11-01 18:02 UTC, stnguyen90 commented on src/routes/docs/advanced/security/backups/+page.markdoc
> +Additionally, some databases support point-in-time recovery
Let's clarify these are the internal backups for disaster recovery

2024-11-04 14:53 UTC, ebenezerdon commented
@stnguyen90 I've pushed a new commit with revision

2024-11-15 21:05 UTC, stnguyen90 approved these changes

2024-11-15 23:07 UTC, stnguyen90 requested changes

2024-11-15 23:07 UTC, stnguyen90 commented on src/routes/docs/advanced/security/backups/+page.markdoc
> +For detailed information about self-managed backup features, configuration options, and restoration procedures, visit our [Backup Documentation](/docs/products/cloud/backups).
This link isn't valid

2024-11-19 22:52 UTC, stnguyen90 approved these changes

2024-11-19 22:52 UTC, merged