Fix: added original removed messaging providers doc page
appwrite/website pull request #1500
Opened 2024-11-19 19:14 UTC by ChiragAgg5k

## What does this PR do?

This PR adds back the originally removed `docs/products/messaging/providers` documentation page. It was originally removed to make the providers more visible and easier to find, but some link according to issue #1479 still redirect to this page and having this page would still be beneficial.

## Test Plan

I have tested that the new page is rendering properly and updated the links to properly redirect to their respective documentations.

## Related PRs and Issues

#1479 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes I have.

<img width="1267" alt="Screenshot 2024-11-20 at 12 44 15 AM" src="https://github.com/user-attachments/assets/c3657a26-179c-4442-be3e-264a54e639e7">

2024-12-13 19:49 UTC, stnguyen90 commented
@ChiragAgg5k, next time, please make sure you ask to be assigned to the issue before submitting a PR.

2024-12-13 19:54 UTC, stnguyen90 requested changes
We also need the link added to the sidebar under Concepts:

https://github.com/appwrite/website/blob/f6f5b4bc834892bed6e76b2455f3c43af40058d7/src/routes/docs/products/messaging/%2Blayout.svelte#L23-L26

2024-12-13 19:54 UTC, stnguyen90 commented on src/routes/docs/products/messaging/providers/+page.markdoc
> +Deliver custom SMS messages to users using TextMagic.
```suggestion
{% cards_item href="/docs/products/messaging/textmagic" title="Textmagic" icon="icon-textmagic" %}
Deliver custom SMS messages to users using Textmagic.
```

2024-12-13 19:57 UTC, ChiragAgg5k commented
sorry about that 😅
will remember next time for sure

2024-12-19 01:11 UTC, stnguyen90 commented on src/routes/docs/products/messaging/providers/+page.markdoc
> +Deliver custom email messages to users using Sendgrid.
```suggestion
{% cards_item href="/docs/products/messaging/sendgrid" title="SendGrid" icon="icon-sendgrid" %}
Deliver custom email messages to users using SendGrid.
```

2024-12-19 04:20 UTC, ChiragAgg5k commented
added the fixes

2024-12-30 23:11 UTC, stnguyen90 commented
@ChiragAgg5k, please make sure to re-request a review when you're all done with your changes:

<img width="465" alt="image" src="https://github.com/user-attachments/assets/fec888e5-2347-4d73-97cf-10224917b4b8" />

2024-12-30 23:13 UTC, stnguyen90 approved these changes

2024-12-30 23:13 UTC, merged