Clarify wildcards restriction and security in serverless functions
appwrite/website pull request #1518
Opened 2024-11-25 21:14 UTC by ebenezerdon

## What does this PR do?

- Clarifies wildcards restriction/security in serverless functions
- Updates the title and description to be more SEO friendly by including the "error" keyword

2024-11-26 10:42 UTC, adityaoberai requested changes

2024-11-27 11:38 UTC, adityaoberai commented
@ebenezerdon trying build once again

2024-11-27 12:20 UTC, adityaoberai commented
@ebenezerdon are you expecting any other reviews?

2024-11-27 13:36 UTC, ebenezerdon commented
> @ebenezerdon are you expecting any other reviews?

No, all good

2024-11-28 06:18 UTC, merged