Add user verification journey to auth docs
appwrite/website pull request #1548
Opened 2024-12-11 13:27 UTC by ebenezerdon

## What does this PR do?
Adds user verification as a new journey in the auth documentation.
- Creates a new verification journey page that documents:
  - Email verification flow
  - Role-based access control
  - Verification events
- Adds user verification to the auth journeys navigation sidebar

## Test Plan
- [x] Run the app and navigate to `/docs/products/auth/verification`
- [x] Verify that the verification journey appears in the auth sidebar under "Journeys"
- [ ] Check that all code examples in the verification page load correctly and are accurate

## Related PRs and Issues
DRL-1115

2024-12-11 15:27 UTC, adityaoberai commented
@ebenezerdon we should also add examples for client SDKs other than web

2024-12-18 20:26 UTC, divanov11 approved these changes

2024-12-19 02:02 UTC, stnguyen90 requested changes

2024-12-19 02:02 UTC, stnguyen90 commented on src/routes/docs/products/auth/verification/+page.markdoc
> +You can restrict resource access to verified users only using permissions through the `user([USER_ID], "verified")` role. This role is automatically assigned after successful verification.
This would restrict for a single user. Let's also mention `users('verified')` to restrict access to all/any verified user.

2025-01-02 12:31 UTC, ebenezerdon commented on src/routes/docs/products/auth/verification/+page.markdoc
> +You can restrict resource access to verified users only using permissions through the `user([USER_ID], "verified")` role. This role is automatically assigned after successful verification.
Thanks, done

2025-01-06 19:47 UTC, ebenezerdon commented on src/routes/docs/products/auth/verification/+page.markdoc
> +To verify a user's email, first send a verification email with a redirect URL. The verification secrets will be appended as query parameters to the redirect URL:
Done

2025-01-06 20:53 UTC, stnguyen90 requested changes
build failure because file doesn't match path.

2025-01-08 04:16 UTC, stnguyen90 approved these changes

2025-01-08 04:16 UTC, merged