Add missing redirect for installation page
appwrite/website pull request #200
Opened 2023-10-04 20:01 UTC by gewenyu99

## What does this PR do?

A secondary fix for this issue: https://github.com/appwrite/appwrite/issues/6437

## Test Plan

2023-10-06 04:09 UTC, sc231997 approved these changes

2023-10-06 11:37 UTC, mesloubi2021 commented
المراجعة مطلوبة واضافة كافة البيانات على شيكات

2023-10-06 16:02 UTC, stnguyen90 requested changes
Redirect works well:

<img width="657" alt="image" src="https://github.com/appwrite/website/assets/1477010/cf50b304-004f-4bdf-ad6b-2bc4cb7027ce">

Would you please fix the extra space?

2023-10-09 09:41 UTC, TorstenDittmann approved these changes

2023-10-09 09:42 UTC, merged