Added new blog
appwrite/website pull request #207
Opened 2023-10-06 09:17 UTC by Haimantika

## What does this PR do?

Adds a new blog for Hacktoberfest

## Test Plan

## Related PRs and Issues

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

2023-10-06 09:20 UTC, ArmanNik requested changes

2023-10-06 09:20 UTC, ArmanNik commented on src/routes/blog/post/behind-the-pr-tales-from-the-open-source-world/+page.markdoc
> +title: Behind the pull request: tales from the open source world
I think if you want to be able to use `:` in your title you need to wrap it in quotes

2023-10-06 09:37 UTC, ArmanNik approved these changes

2023-10-30 11:27 UTC, TGlide commented on src/routes/blog/post/behind-the-pr-tales-from-the-open-source-world/+page.markdoc
> +### Inspiring stories from the community
Hi, we should be using `#` for headings and `###` for sub-headings.

2023-10-30 11:56 UTC, TGlide approved these changes

2023-10-30 11:57 UTC, merged