Fixed incosistency in pricing details
appwrite/website pull request #210
Opened 2023-10-06 13:08 UTC by Haimantika

## What does this PR do?

Fixes inconsistency in pricing tier

## Test Plan

NA

## Related PRs and Issues
Fixes https://github.com/appwrite/appwrite/issues/6494

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-10-06 13:11 UTC, ArmanNik approved these changes

2023-10-06 15:24 UTC, stnguyen90 requested changes

2023-10-06 15:24 UTC, stnguyen90 commented on src/routes/pricing/+page.svelte
> +												<li><span>10GB bandwidth</span></li>
There's already another PR for this fix: https://github.com/appwrite/website/pull/205. Would you please fix the function execution inconsistency?

2023-10-09 09:38 UTC, TorstenDittmann approved these changes

2023-10-09 09:38 UTC, merged