📚 Documentation: Tutorial for Angular
appwrite/website pull request #219
Opened 2023-10-09 11:47 UTC by aakashraj01

## What does this PR do?

Added Tutorial for a functioning app with Angular in the Docs

## Test Plan

The Tutorial can be found in the route /docs/tutorials/angular/step-1

## Related PRs and Issues

#81 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-10-10 15:58 UTC, gewenyu99 requested changes

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-1/+page.markdoc
> +2. Have [Node.js](https://nodejs.org/en) and [NPM](https://www.npmjs.com/) installed on your computer
We should add the Angular CLI as a prerequisite to install

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-2/+page.markdoc
> +Create a Angular app with the `ng-new` command.
`ng-new` or `ng new`?

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-2/+page.markdoc
> +ng new ideas-tracker && cd ideas-tracker
Specify is they should use typescript vs javascript

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-4/+page.markdoc
> +Create a new file `src/app/user.service.js` and add the following code to it.
This should be ts, same as the getting started for angular

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-4/+page.markdoc
> +import { RouterModule, Routes } from '@angular/router';
Make sure you show where to add the router module imports in the AppsModules like:

```ts
import { FormsModule } from '@angular/forms';
...
@NgModule({
  declarations: [
    // ...
  ],
  imports: [
    // ...
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-5/+page.markdoc
> +- a logout button if the user is logged in.
These are sentences :) Please add capital letters in the first letter

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-5/+page.markdoc
> +@Component({
Should this be in multiple files for consistency? What is the style guide on Angular say?

2023-10-10 15:58 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-6/+page.markdoc
> +# Create collection
Missing ID with the {% #ksakdjf %} format

2023-10-25 23:58 UTC, aakashraj01 commented
> @aakashraj01 Are you still working on this?

Yes @gewenyu99 . I m still working and have done most of the review comment changes :)

2023-10-26 02:23 UTC, gewenyu99 commented
> > @aakashraj01 Are you still working on this?
> 
> Yes @gewenyu99 . I m still working and have done most of the review comment changes :)

Don't forget to re-request review and make sure you build passes!

2023-10-28 18:17 UTC, aakashraj01 commented
Hey @gewenyu99 . I have made all the changes as per your review comments suggestions. Please have a review over the PR :)

2023-10-29 21:00 UTC, gewenyu99 requested changes
Hey, there's a lot of missing and incorrect information I found and could not properly follow the tutorial.

Please carefully follow your own tutorial from scratch and make sure it works so we can accept it in time for Hacktoberfest!

2023-10-29 21:00 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-4/+page.markdoc
> +import { account } from './appwrite.service';
That path looks wrong

2023-10-29 21:00 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-4/+page.markdoc
> +    await account.create(email, password);
This is missing arguments. account.create requires 3 arguments at minimum

2023-10-29 21:00 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-4/+page.markdoc
> +Ensure you have the FormsModule imported in your `app.module.tsx` to use `[(ngModel)]` for two-way data binding.
Please give more details here. Take inspiration from here:
https://appwrite.io/docs/quick-starts/angular#step-5

2023-10-29 21:00 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-5/+page.markdoc
> +Update the `AppComponent` in `src/app/app.component.tsx`:
I don't have this file. I have 3 files, are you missing setup instructions?
<img width="228" alt="Screenshot 2023-10-29 at 4 40 32 PM" src="https://github.com/appwrite/website/assets/29069505/d68c89ac-03d8-4f07-bcf9-b019911aaf48">

2023-10-29 21:00 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-5/+page.markdoc
> +Update the `AppComponent` in `src/app/app.component.tsx`:
Also should we really use TSX? What is the recommended default for Angular, can we stick to it?

2023-10-29 21:00 UTC, gewenyu99 commented on src/routes/docs/tutorials/angular/step-5/+page.markdoc
> +    <app-navbar></app-navbar> <!-- Add the navbar before page content -->
Missing imports here.

2023-10-31 22:44 UTC, gewenyu99 commented
Hey,

Due to time constraints, I'm going to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.

When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.

Thanks for helping us improve Appwrite!

2023-11-14 02:43 UTC, tessamero commented
Hello @aakashraj01 ,

Thank you for your contribution to Hacktoberfest 2023! We've noticed that your PR is still pending and requires some updates based on our engineering team's feedback.

We would love to see your PR successfully merged and send you the Appwrite swag as a token of appreciation. To remain eligible for the swag, please address the pending suggestions and/or ensure the tests pass  by **Friday, November 17th**. If the PR isn't updated by then, we will unfortunately have to close it due to the end of the Hacktoberfest event.

Looking forward to your updates and thank you!

2024-04-09 02:53 UTC, aakashraj01 commented
> Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 
> 
> 
> 
> Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

Hey @gewenyu99 . My discord username is Aakash Raj#8138

2026-09-21 12:31 UTC, closed without merging