Added Flutter Authentication Deepdive
appwrite/website pull request #275
Opened 2023-10-25 13:34 UTC by Rohit-RA-2020

## What does this PR do?

Add Flutter Authentication Deep-dive

## Test Plan

## Related PRs and Issues

#92 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes

2023-10-25 13:36 UTC, Rohit-RA-2020 commented
Hey @gewenyu99 can you review this 😄

2023-10-26 15:14 UTC, Rohit-RA-2020 commented
Closes #92

2023-10-26 15:56 UTC, gewenyu99 requested changes
Hey, great job on this PR, looking clean. 

I will try to follow this start to finish later to audit the examples in more detail.

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-1/+page.markdoc
> +difficulty: beginner
Intermediate maybe

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-2/+page.markdoc
> +Creating project my_flutter_project...
I love this, but maybe it's excessively long. Idk if this is overly helpful.

Up to you.

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-2/+page.markdoc
> +## Adding Appwrite to Your Flutter App
Missing {% #header-label-text %}

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-3/+page.markdoc
> +        .setSelfSigned(status: true);
We're gonna suggest they do this against cloud so the appwrite endpoint should default to cloud and setSelfSigned should not be set :D

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-3/+page.markdoc
> +For example, your `lib/constants.dart` file might look something similar to this.
Let's avoid confusing and just suggest they use constants for now :)

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-4/+page.markdoc
> +Now Using `FutureBuilder` and providing the `account.get()` method as the future, we can check if the user is logged in. If the user is logged in, we can show the welcome message, otherwise we can sh
I love the wai you explain things here, great job.

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-7/+page.markdoc
> +If you want to see these authentication concepts applied in a more robust manner, you can see them in action in this [demo app]().
Missing link heeheee, use your repo for now, we'll fork it from our org later.

2023-10-26 15:56 UTC, gewenyu99 commented on src/routes/docs/tutorials/flutter-auth/step-7/+page.markdoc
> +## Other authentication methods
For all, remember to include {% #heading %} so table of contents popular

2023-10-31 22:39 UTC, gewenyu99 commented
Hey,

Due to time constraints, I'm going to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.

When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.

Thanks for helping us improve Appwrite!

2023-11-17 21:58 UTC, merged

2024-04-08 20:14 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-09 05:29 UTC, Rohit-RA-2020 commented
Hey @gewenyu99, 
Thanks for reaching out. Here's my Discord username : **rohitranjan**

2024-04-19 16:08 UTC, gewenyu99 commented
Will be reaching out soon :)