doc: implemented Appwrite auth functionalities with Vuejs
appwrite/website pull request #301
Opened 2023-10-30 07:51 UTC by Vaibhav91one

## What does this PR do?

This PR provides a tutorial for how to use appwrite authentication with Vue

## Test Plan

I have made the app while creating the tutorial.

## Related PRs and Issues
-

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-10-30 15:04 UTC, gewenyu99 requested changes
Sorry, why are you removing the vue js tutorial?

2023-10-30 15:05 UTC, gewenyu99 commented
Please also fix your build before re-requesting review. Do a `pnpm run build`

Thanks!

2023-10-30 17:41 UTC, Vaibhav91one commented
> Sorry, why are you removing the vue js tutorial?

Should I make another folder for the vue-auth?

2023-10-30 17:41 UTC, Vaibhav91one commented
> Please also fix your build before re-requesting review. Do a `pnpm run build`
> 
> Thanks!

Okay will do.

2023-10-30 17:43 UTC, gewenyu99 commented
> > Sorry, why are you removing the vue js tutorial?
> 
> Should I make another folder for the vue-auth?

Yes, follow the convention here: https://appwrite.io/docs/tutorials/sveltekit-auth/step-1

Still hidden for now, but should be basically like this.

2023-10-30 17:43 UTC, Vaibhav91one commented
> > > Sorry, why are you removing the vue js tutorial?
> > 
> > 
> > Should I make another folder for the vue-auth?
> 
> Yes, follow the convention here: https://appwrite.io/docs/tutorials/sveltekit-auth/step-1
> 
> Still hidden for now, but should be basically like this.

Okay on it.

2023-10-30 19:50 UTC, Vaibhav91one commented
Hey @gewenyu99 I seem to be getting a parse error when building for a specific code snippet
![image](https://github.com/appwrite/website/assets/108279746/8335c640-2b5c-43e2-928a-8d7186077be4)

and when I remove that code snippet, the following error comes up:
![image](https://github.com/appwrite/website/assets/108279746/1912544b-c26d-4473-b42a-46a27cd4f8d4)

2023-10-30 21:19 UTC, gewenyu99 commented
> and when I remove that code snippet, the following error comes up:

Make sure you build on your local machine, code spaces will run out of space :P

2023-10-31 04:53 UTC, Vaibhav91one commented
> > and when I remove that code snippet, the following error comes up:
> 
> Make sure you build on your local machine, code spaces will run out of space :P

Okay, I am building on my local machine only, will try once again.

2023-10-31 08:55 UTC, Vaibhav91one commented
@gewenyu99 I have done some changes and successful build the project. I have made another folder vue-auth and kept the vue tutorial as it is back to the project.

2023-10-31 14:14 UTC, gewenyu99 commented
@Vaibhav91one Thank you, it's the last day of Hacktoberfest, I'm gonna tentatively mark this Hacktoberfest accepted so you get credits from DO.

I'll review and continue to work with you on this PR, and when it's merged, you'll get contacted for swags :)

2023-10-31 14:16 UTC, gewenyu99 commented on src/routes/docs/tutorials/vue-auth/step-1/+page.markdoc
> +## Appwrite: The backend you'll never have to build or maintain.
Please follow convention from other tutorials for what should be in this first page.

2023-10-31 14:16 UTC, gewenyu99 commented on src/routes/docs/tutorials/vue-auth/step-1/+page.markdoc
> +difficulty: medium
```suggestion
difficulty: intermediate
```

2023-10-31 14:28 UTC, gewenyu99 reviewed
Hey, this is a great start.

Before I go in with more reviews, we really care about consistency, and this tutorial's structure is unnecessarily different from what we have in svelte kit.

<img width="193" alt="Screenshot 2023-10-31 at 10 25 39 AM" src="https://github.com/appwrite/website/assets/29069505/9c18e8ee-543e-4cbc-9c42-b96f61d983db">

I like that you also implemented password recovery and verification + protected routes.

They should be further headings:
- Password recovery
- User verification
- Protected routes.


So your headings should be:
- Authentication with SvelteKit
- Create project
- Initialize SDK
- Check if logged in
- Create login page
- Create signup page
- Password recovery
- User verification
- Protected routes
- All set

2023-10-31 14:28 UTC, gewenyu99 commented on src/routes/docs/tutorials/vue-auth/step-2/+page.markdoc
> +You can create a Vue project using [Vue](https://vuejs.org/guide/quick-start.html).
Missing headings

2023-10-31 14:28 UTC, gewenyu99 commented on src/routes/docs/tutorials/vue-auth/step-2/+page.markdoc
> +## Adding Appwrite to Your Vue App
Headings should be sentence case.

Missing `{% #id %}` tags

2023-10-31 14:28 UTC, gewenyu99 commented on src/routes/docs/tutorials/vue-auth/step-3/+page.markdoc
> +# Create project {% #create-project %}
Can we just reuse step 2-3 from the vue tutorial. They don't need to be different other than description.

2023-10-31 14:28 UTC, gewenyu99 commented on src/routes/docs/tutorials/vue-auth/step-4/+page.markdoc
> +Since, we chose pinia for state management during the installatin process.So, we have already setuped our store.
```suggestion
Since, we chose pinia for state management during the installatin process. So, we have already setuped our store. 
```

2023-10-31 19:03 UTC, Vaibhav91one commented
@gewenyu99 Okay will do the changes in the morning  and Thank you for considering it for hacktoberfest.
(Good night🌙)

2023-10-31 22:41 UTC, gewenyu99 commented
Hey,

Due to time constraints, I'm going to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.

When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.

Thanks for helping us improve Appwrite!

2023-11-07 07:04 UTC, Vaibhav91one commented
@gewenyu99 I have made the changes. 
1. Corrections
2. Steps added as told

2023-11-17 22:01 UTC, gewenyu99 commented
Hey, looks like a good start for the tutorial. I'll merge this into a branch to continue working on this on our end. Thank you so much!

2023-11-17 22:03 UTC, merged

2023-11-29 05:43 UTC, Vaibhav91one commented
> Hey, looks like a good start for the tutorial. I'll merge this into a branch to continue working on this on our end. Thank you so much!

Your welcome and Thank you for the guidance. 🚀

2024-01-24 07:44 UTC, Vaibhav91one commented
Hey @gewenyu99 I was just curious that, is this still under review? If there is anything I can do to help, feel free to ask.

2024-04-08 20:14 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-09 16:25 UTC, Vaibhav91one commented
> Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship.
> 
> Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

Profile Link: https://discordapp.com/users/762914716652797982
Username: averagevaibhav

2024-04-19 16:09 UTC, gewenyu99 commented
Will reach out soon. Appreciate your patience!