Doc: Removed alt attributes in cards
appwrite/website pull request #303
Opened 2023-10-30 15:31 UTC by Sweetdevil144

## What does this PR do?
Removes `alt` attributes from cards in [this](https://appwrite.io/docs) section of website.
> An empty alt attribute hides the image from assistive technology so it does not add unnecessary noise within the link. Removing the alt attribute would result in the images URL being read out which would make the problem worse!
(Provide a description of what this PR does.)

## Related PRs and Issues
Fixes #284 
(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes
(Write your answer here.)

2023-10-30 18:32 UTC, Arindam200 approved these changes

2023-10-31 15:41 UTC, TGlide commented on src/routes/docs/+page.svelte
> +                alt: ''
If we never want to have the alt in these images, we probably should not expect it as a prop in `CodeCard`

2023-11-01 14:03 UTC, Sweetdevil144 commented
@TGlide can you review it?

2023-11-03 13:58 UTC, TGlide commented on src/routes/docs/CodeCard.svelte
>          cover: {
Cover can be a string only, since it only has a single attribute

2023-11-06 14:34 UTC, TGlide requested changes
The images seem to be missing: 
![image](https://github.com/appwrite/website/assets/26071571/12b7716b-3301-40ca-a891-009a9c1a9e4b)

2023-11-06 14:34 UTC, TGlide commented on src/routes/docs/tutorials/+page.svelte
> +                                <img src="/images/platforms/{$themeInUse}/vue.svg" />
Why was alt removed? An empty alt signifies the image is only decorative, which is desired in this case.

2023-11-06 17:08 UTC, TGlide requested changes

2023-11-06 17:08 UTC, TGlide commented on src/routes/docs/+page.svelte
> +            src: '/images/tutorials/react.png',
I think cover worked best. It may be confusing to see href and src attributes in the same object

2023-11-06 20:17 UTC, merged

2024-04-08 20:15 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-08 20:19 UTC, Sweetdevil144 commented
Hey,

Sweetdevil144#8236

Thanks :)

2024-04-14 19:49 UTC, Sweetdevil144 commented
@gewenyu99 Updates?

2024-04-19 16:10 UTC, gewenyu99 commented
> @gewenyu99 Updates?

Will reach out soon. Putting some last things together. Appreciate the patience!