Added URL shortener blog
appwrite/website pull request #335
Opened 2023-11-08 10:40 UTC by Haimantika

## What does this PR do?

Adds URL shortener function template blog

## Test Plan

NA

## Related PRs and Issues

NA

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-11-08 13:59 UTC, TorstenDittmann requested changes

2023-11-08 13:59 UTC, TorstenDittmann commented on src/routes/blog/post/adding-url-shortener-function/+page.markdoc
> +/images/blog/adding-url-shortener/functions.png
the images here need to use the markdown image syntax

2023-11-08 13:59 UTC, TorstenDittmann commented on src/routes/blog/post/adding-url-shortener-function/+page.markdoc
> +- SHORT_BASE_URL
here we can use inline code

```suggestion
- `APPWRITE_API_KEY`
- `SHORT_BASE_URL`
```

2023-11-08 13:59 UTC, TorstenDittmann commented on static/images/blog/adding-url-shortener/Add-a-URL-Shortener-to-your-Application-with-Functions.png
lets use lower case file names

2023-11-08 13:59 UTC, TorstenDittmann commented on static/images/blog/adding-url-shortener/URL-shortener.png
lets use lowercase filenames

2023-11-14 13:07 UTC, LauraDuRy commented on src/routes/blog/post/adding-url-shortener-function/+page.markdoc
> +Appwrite Functions are user-defined functions that can start small and scale big, deploying automatically from source control. With the introduction of function templates, you can quickly add new int
Mistake in punctuation

2023-11-14 13:33 UTC, TorstenDittmann approved these changes

2023-11-14 13:33 UTC, merged