Fix formatting & add endpoints to refereneces
appwrite/website pull request #382
Opened 2023-11-23 17:11 UTC by TGlide

2023-11-23 17:19 UTC, TorstenDittmann approved these changes
Please make sure it goes through a design review 👍🏻

2023-11-23 17:19 UTC, TorstenDittmann commented on src/lib/utils/specs.ts
> +    console.log({ api });
leftover

2023-11-23 17:19 UTC, TorstenDittmann commented on src/lib/utils/specs.ts
> +        // console.log({ method, value });
leftover

2023-11-23 19:42 UTC, eldadfux commented
Reminder to add some padding between the sticky top border and the `path` code block

2023-11-23 19:46 UTC, eldadfux commented
We're also missing the `/v1/` prefix for the paths.

2023-11-23 22:27 UTC, gewenyu99 approved these changes
Nice <3

Maybe address should be on the left tbh, let's talk about this with Chen later.

2023-11-30 16:34 UTC, gewenyu99 requested changes
@TGlide Check Asana, there are some changes Chen asked for :)

2023-12-18 15:03 UTC, gewenyu99 commented
![image](https://github.com/appwrite/website/assets/29069505/0712f6ec-7d32-437a-9641-fae39a9cd27a)
One last comment, can we make the copy button here select only the path not the method?

Copy `/getAccount` vs `GET /getAccount` as a figurative example.

2023-12-18 15:08 UTC, gewenyu99 approved these changes
Other than my comment about copy, if that's difficult/not possible right now, we can merge this as is.

2023-12-18 15:27 UTC, gewenyu99 commented
LGTM, paste is fixed

2023-12-18 15:58 UTC, merged