Fix migration cloud to self-hosted
appwrite/website pull request #385
Opened 2023-11-24 22:22 UTC by gewenyu99

## What does this PR do?

@Haimantika This should fix https://github.com/appwrite/website/issues/231
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-11-30 17:32 UTC, stnguyen90 requested changes

2023-11-30 17:32 UTC, stnguyen90 commented on src/routes/docs/advanced/migrations/cloud/+page.markdoc
> +
Stuff after needs to be deleted?

2023-12-18 13:26 UTC, TGlide approved these changes

2023-12-18 13:32 UTC, TGlide commented on src/routes/docs/advanced/migrations/cloud/+page.markdoc
> +
@stnguyen90 I've removed them

2023-12-18 21:13 UTC, stnguyen90 requested changes
See https://github.com/appwrite/website/pull/385#discussion_r1430651532

2023-12-21 01:22 UTC, stnguyen90 approved these changes
I'm not sure why the tests are failing as I built it myself and it worked out fine.

2023-12-26 10:22 UTC, merged