Fix React tutorial create account
appwrite/website pull request #438
Opened 2023-12-20 20:28 UTC by gewenyu99

## What does this PR do?

Fixes a bad line of code.
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-12-20 23:58 UTC, stnguyen90 requested changes

2023-12-20 23:58 UTC, stnguyen90 commented on src/routes/docs/tutorials/react/step-4/+page.markdoc
> +		await account.create(ID.unique(), email, password);
```suggestion
    await account.create(ID.unique(), email, password);
```

2023-12-28 00:47 UTC, stnguyen90 requested changes

2023-12-28 00:47 UTC, stnguyen90 commented on src/routes/docs/tutorials/react/step-4/+page.markdoc
> +    await account.create(ID.unique(), email, password);
ID also needs to be included in the import above.

2024-01-16 15:14 UTC, gewenyu99 commented on src/routes/docs/tutorials/react/step-4/+page.markdoc
> +import { account, ID } from "../appwrite";
<img width="791" alt="Screenshot 2024-01-16 at 10 13 48 AM" src="https://github.com/appwrite/website/assets/29069505/b9d4c2d9-d794-406f-a571-3f07d67179a1">
Yes, we wrap and export for all quick starts

2024-01-16 19:41 UTC, stnguyen90 approved these changes

2024-01-16 19:59 UTC, merged