1.5.x docs
appwrite/website pull request #440
Opened 2023-12-21 02:22 UTC by gewenyu99

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-02-01 01:30 UTC, gewenyu99 commented on src/routes/docs/products/auth/mfa/+page.markdoc
> +[TODO @TorstenDittmann need some advice here, what's the steps?]
@TorstenDittmann this is the MFA journey docs we added. Please take a look. Need help double checking the flow + the missing auth methods :)

2024-02-10 00:06 UTC, stnguyen90 requested changes

2024-02-10 00:06 UTC, stnguyen90 commented on src/routes/docs/products/messaging/targets/+page.markdoc
> +Verified phone numbers for users that signed up with [Phone OPT](/docs/products/auth/phone-sms) login will already have a phone target.
```suggestion
Verified phone numbers for users that signed up with [Phone OTP](/docs/products/auth/phone-sms) login will already have a phone target.
```

2024-02-13 19:31 UTC, eldadfux commented on src/routes/docs/products/auth/server-side-rendering/+page.markdoc
> +description: How to implement SSR authentication with Appwrite
Why do we start with a question. This should be a regular docs title.

2024-02-14 18:30 UTC, closed without merging