chore: update references
appwrite/website pull request #510
Opened 2024-01-10 16:41 UTC by christyjacob4

## What does this PR do?

Rename the references section to **API Reference** to make it more verbose and easy to discover

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-01-10 16:42 UTC, christyjacob4 commented
![Screenshot 2024-01-10 at 8 42 40 PM](https://github.com/appwrite/website/assets/20852629/bab81108-f477-4b89-9c2f-391c1d81c7a0)


![Screenshot 2024-01-10 at 8 42 52 PM](https://github.com/appwrite/website/assets/20852629/8793103d-45b5-4c41-81b3-be0ffddaf54f)

2024-01-10 20:14 UTC, gewenyu99 requested changes

2024-01-10 20:14 UTC, gewenyu99 commented on src/lib/components/Search.svelte
> +            h1: 'API Reference',
```suggestion
            h1: 'API reference',
```

We use sentence case! rest looks good.

2024-01-12 09:36 UTC, eldadfux approved these changes

2024-01-12 09:36 UTC, merged