changelog update Ruby SDK
appwrite/website pull request #536
Opened 2024-01-19 13:13 UTC by LauraDuRy

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-01-19 14:47 UTC, eldadfux requested changes

2024-01-19 14:47 UTC, eldadfux commented on src/routes/changelog/(entries)/2024-01-19.markdoc
> +We’ve just released a new Ruby SDK with fixes for the database service.
```suggestion
We’ve just released a new Ruby SDK with fixes for the databases service.
```

2024-01-19 14:47 UTC, eldadfux commented on src/routes/changelog/(entries)/2024-01-19.markdoc
> +- Fix null parameters being passed to API
```suggestion
- Fix null parameters being passed to the API
```

2024-01-19 14:47 UTC, eldadfux commented on src/routes/changelog/(entries)/2024-01-19.markdoc
> +View the [pull request](https://github.com/appwrite/sdk-for-ruby/compare/10.1.0...10.1.1) on GitHub for the source code.
```suggestion
View the [changes](https://github.com/appwrite/sdk-for-ruby/compare/10.1.0...10.1.1) on GitHub.
```

2024-01-19 14:47 UTC, eldadfux commented on src/routes/changelog/(entries)/2024-01-19.markdoc
> +- Fix `require` in documentation
Not sure what this means

2024-01-22 09:36 UTC, TorstenDittmann approved these changes

2024-04-11 09:13 UTC, closed without merging