Cors blog
appwrite/website pull request #541
Opened 2024-01-19 22:47 UTC by divanov11

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-01-22 17:36 UTC, LauraDuRy commented on src/routes/blog/post/cors-error/+page.markdoc
> +I want to address an issue I've seen popping up on stack overflow and the appwrite discord server and address some of the reasons you may be getting this error, and walk you through some of the steps
Capitalize `Stack Overflow` `Appwrite` and `Discord`

2024-01-22 17:36 UTC, LauraDuRy commented on src/routes/blog/post/cors-error/+page.markdoc
> +This happens because our server has not added site B, `myfrontend.com` to it's list of allowed origins, therefor any request coming from a URL that is not listed in our servers allowed origins will b
`therefor` should be `therefore`?

2024-01-22 17:36 UTC, LauraDuRy commented on src/routes/blog/post/cors-error/+page.markdoc
> +First, you'll want to check your appwrite console to make sure you have added a hostname and are making a request from the correct hostname. Make sure you have added a platform in your appwrite conso
capatilize Appwrite and Console

2024-01-22 17:36 UTC, LauraDuRy commented on src/routes/blog/post/cors-error/+page.markdoc
> +- Disabled CORS in browser.  (I’ve seen people have this issue with browser extensions)
Add another line with resources:
- docs
- Discord
- YouTube

2024-01-23 10:39 UTC, PineappleIOnic commented on src/routes/blog/post/cors-error/+page.markdoc
> +- [Appwrite Discord server](appwrite.io/discord)
```suggestion
- [Appwrite Discord server](https://appwrite.io/discord)
```

2024-01-23 10:39 UTC, PineappleIOnic commented on src/routes/blog/post/cors-error/+page.markdoc
> +- [Threads](appwrite.io/threads)
```suggestion
- [Threads](https://appwrite.io/threads)
```

2024-01-25 20:46 UTC, divanov11 commented
@LauraDuRy & @PineappleIOnic is there anything holding this article from being posted?

2024-01-26 10:37 UTC, PineappleIOnic approved these changes
On a code level it looks good to me

2024-01-26 12:08 UTC, LauraDuRy commented
Added correct youtube link, all good now

2024-01-29 18:08 UTC, gewenyu99 requested changes

2024-01-29 18:08 UTC, gewenyu99 commented on src/routes/blog/post/cors-error/+page.markdoc
> +I want to address an issue I've seen popping up on stack overflow and the appwrite discord server and address some of the reasons you may be getting this error, and walk you through some of the steps
@divanov11 Take a look here at Laura's comments.

2024-01-29 18:08 UTC, gewenyu99 commented on src/routes/blog/post/cors-error/+page.markdoc
> +## **Understanding CORS**
We start with `#` in the markdown -> It will be transformed to `##` Please un bold the  heading.

2024-01-29 18:08 UTC, gewenyu99 commented on src/routes/blog/post/cors-error/+page.markdoc
> +### 1 - Origin not set in Console
Move all you headings on level higher

## -> #

### -> ##

We render # as ##

2024-01-29 19:41 UTC, Kilo-Loco reviewed
Great read! Made some suggested changes.

2024-01-29 19:41 UTC, Kilo-Loco commented on static/images/blog/cors-error/cors_example.png
Typo: Server
nit: I'm wondering if we could use a different font to increase readability. This diagram is extremely helpful to people learning about CORS but people with vision any level of vision impairment may have difficulty reading this particular font. That said, this visualized architecture on an Appwrite blog is a signature that says this is a "Dennis Ivy" blog which is always a good read.

2024-01-29 19:41 UTC, Kilo-Loco commented on src/routes/blog/post/cors-error/+page.markdoc
> +Before we start debugging this, let's talk about what CORS error is.
The following section teaches the reader what CORs is before referring to the error.

```suggestion
Before we start debugging this, let's talk about what CORS is.
```

2024-01-29 19:41 UTC, Kilo-Loco commented on src/routes/blog/post/cors-error/+page.markdoc
> +First, you'll want to check your Appwrite Console to make sure you have added a hostname and are making a request from the correct hostname. Make sure you have added a platform in your Appwrite conso
Overview should be capitalized in this context.

```suggestion
First, you'll want to check your Appwrite Console to make sure you have added a hostname and are making a request from the correct hostname. Make sure you have added a platform in your Appwrite console by going to the "Overview" tab, select your platform (Add one if you have not yet), and then ensure you have added a hostname.
```

2024-01-30 16:24 UTC, gewenyu99 approved these changes

2024-01-30 16:31 UTC, gewenyu99 commented on static/images/blog/cors-error/cors_example.png
Great catch 😆

2024-01-30 17:37 UTC, divanov11 commented on static/images/blog/cors-error/cors_example.png
Good catch! I fixed it in the video before release but forgot to update the blog image. I agree with the font issue. I'm using Excalidraw at the moment so I'll see if I can add custom fonts

2024-01-30 19:38 UTC, merged