GitHub starts update 39k
appwrite/website pull request #568
Opened 2024-02-01 07:49 UTC by LauraDuRy

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-02-01 10:28 UTC, adityaoberai requested changes
A couple more places where the numbers need to be updated

- https://github.com/appwrite/website/blob/ccdef373cce20df5b924ddc614518beb3c3b1a1f/src/lib/animations/OpenSource.svelte#L187-L188

- https://github.com/appwrite/website/blob/ccdef373cce20df5b924ddc614518beb3c3b1a1f/src/routes/community/%2Bpage.svelte#L546

2024-02-01 10:30 UTC, adityaoberai commented
@LauraDuRy once these are updated too, let me know and I'll approve :)

2024-02-01 13:38 UTC, eldadfux approved these changes

2024-02-06 10:50 UTC, LauraDuRy commented
@adityaoberai updated. please check

2024-02-07 10:46 UTC, closed without merging