feat: ssr demos
appwrite/website pull request #593
Opened 2024-02-09 11:52 UTC by loks0n

Server side auth tutorials for:
- [x] Nextjs
- [] Nuxt
- [] Astro

2024-02-09 15:37 UTC, gewenyu99 commented on src/routes/docs/tutorials/nextjs-ssr-auth/+page.ts
Looks like you converted some files accidetally?

2024-02-09 15:51 UTC, gewenyu99 requested changes

2024-02-09 15:51 UTC, gewenyu99 commented on src/routes/docs/tutorials/nextjs-ssr-auth/step-1/+page.markdoc
> +If you're inspired and wish to follow along, make sure you've followed [Start with Next.js](https://appwrite.io/docs/quick-starts/sveltekit) first.
Link is wrong

2024-02-09 15:51 UTC, gewenyu99 commented on src/routes/docs/tutorials/nextjs-ssr-auth/step-2/+page.markdoc
> +Create a react project using [Next.js](https://kit.svelte.dev/docs/creating-a-project).
Link is wrong

2024-02-09 15:51 UTC, gewenyu99 commented on src/routes/docs/tutorials/nextjs-ssr-auth/step-3/+page.markdoc
> +export const SESSION_COOKIE = "a_session";
What does this do?

2024-02-09 15:51 UTC, gewenyu99 commented on src/routes/docs/tutorials/nextjs-ssr-auth/step-3/+page.markdoc
> +You can get the values for these variables from the Appwrite console. The `PUBLIC_APPWRITE_ENDPOINT` is the endpoint of your Appwrite server, and the `PUBLIC_APPWRITE_PROJECT` is the ID of the projec
```suggestion
You can get the values for these variables from the Appwrite console. The `PUBLIC_APPWRITE_ENDPOINT` is the endpoint of your Appwrite server, and the `PUBLIC_APPWRITE_PROJECT` is the ID of the project you want to use. The `APPWRITE_KEY` is an Appwrite API key with the necessary permissions to read and write accounts and sessions.
```

2024-02-09 17:35 UTC, loks0n commented on src/routes/docs/tutorials/nextjs-ssr-auth/step-1/+page.markdoc
> +If you're inspired and wish to follow along, make sure you've followed [Start with Next.js](https://appwrite.io/docs/quick-starts/sveltekit) first.
fixed

2024-02-12 19:38 UTC, loks0n commented on src/routes/docs/tutorials/nextjs-ssr-auth/+page.ts
These are intentional, GH is just showing a weird changelog

2024-02-12 19:38 UTC, loks0n commented on src/routes/docs/tutorials/nextjs-ssr-auth/step-2/+page.markdoc
> +Create a react project using [Next.js](https://kit.svelte.dev/docs/creating-a-project).
Fixed

2024-02-12 20:00 UTC, merged