adding blog "everyone can do devrel but should they?"
appwrite/website pull request #611
Opened 2024-02-14 10:06 UTC by SumeyraBulut

2024-02-14 14:43 UTC, PineappleIOnic approved these changes

2024-02-15 12:03 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +One thing that I can say, having spent three years in communities and over ten months as a DevRel professional at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy.
I'll definitely need to update this opening line xD

2024-02-15 12:04 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +category: culture
I don't think this would be the appropriate category

It might make sense to create a new one called `devrel` or `community`

2024-02-15 12:05 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +Check out Appwrite as the backend for your next [web](https://appwrite.io/docs/getting-started-for-web), [Flutter](https://appwrite.io/docs/getting-started-for-flutter), or [server-side](https://appw
These are all older links

2024-03-08 11:45 UTC, adityaoberai requested changes
@SumeyraBulut I've added all my update suggestions

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +category: culture
```suggestion
category: devrel
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +One thing that I can say, having spent three years in communities and over ten months as a DevRel professional at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy.
```suggestion
One thing that I can say, having spent five years in communities and over two years as a Developer Advocate at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy. DevRel is something we can do by helping developers in our communities, sharing knowledge through our content, or writing code and building projects. That being said, should everyone be rushing towards a job in Developer Relations? Recently, I have observed a bubble developing around this space. I want to take this blog as an opportunity to share my opinion on whether everyone should chase DevRel as a career.
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +- [Appwrite Documentation](https://appwrite.io/docs)
```suggestion
## A little about Appwrite

[Appwrite](http://appwrite.io/) is an open-source Backend-as-a-Service (BaaS) platform that lets you add Authentication, Databases, Functions, and Storage to your product and build any application at any scale, own your data, and use your preferred coding languages and tools.

Learn more about Appwrite:

- [Appwrite Docs](https://appwrite.io/docs)
- [Appwrite Discord community](https://appwrite.io/discord)
- [Appwrite YouTube channel](https://youtube.com/@appwrite)
- [Appwrite GitHub repo](https://github.com/appwrite/appwrite)
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +## A little about Appwrite
```suggestion
# A little about Appwrite
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +## Taking this decision
```suggestion
# Taking this decision
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +## Is DevRel just another fad?
```suggestion
# Is DevRel just another fad?
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +### Building communities
```suggestion
## Building communities
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +### Creating content
```suggestion
## Creating content 
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +### Writing code
```suggestion
## Writing code 
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +## What experience should DevRel practitioners possess
```suggestion
# What experience should DevRel practitioners possess 
```

2024-03-08 11:45 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +## Understanding DevRel
```suggestion
# Understanding DevRel
```

2025-06-09 20:04 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +One thing that I can say, having spent five years in communities and over two years as a Developer Advocate at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy. Dev
```suggestion
One thing that I can say, having spent six years in communities and over three years as a Developer Advocate at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy. DevRel is something we can do by helping developers in our communities, sharing knowledge through our content, or writing code and building projects. That being said, should everyone be rushing towards a job in Developer Relations? Recently, I have observed a bubble developing around this space. I want to take this blog as an opportunity to share my opinion on whether everyone should chase DevRel as a career.
```

2025-06-09 20:04 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +>
```suggestion
```

2025-06-09 21:05 UTC, adityaoberai commented on src/routes/blog/post/everyone-can-do-devrel-but-should-they/+page.markdoc
> +One thing that I can say, having spent six years in communities and over three years as a Developer Advocate at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy. De
```suggestion
One thing that I can say, having spent five years in communities and over two years as a Developer Advocate at Appwrite, is that Developer Relations (or DevRel) isn’t just a job but a philosophy. DevRel is something we can do by helping developers in our communities, sharing knowledge through our content, or writing code and building projects. That being said, should everyone be rushing towards a job in Developer Relations? Recently, I have observed a bubble developing around this space. I want to take this blog as an opportunity to share my opinion on whether everyone should chase DevRel as a career.
```

2025-06-09 21:05 UTC, adityaoberai approved these changes

2025-06-09 21:05 UTC, merged