Enums announcement
appwrite/website pull request #658
Opened 2024-02-21 13:20 UTC by LauraDuRy

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-02-21 13:21 UTC, LauraDuRy commented
Need to update the docs link

2024-02-28 07:59 UTC, adityaoberai requested changes
@LauraDuRy mostly looks good, just have one change recommendation

2024-02-28 07:59 UTC, adityaoberai commented on src/routes/blog/post/introducing-enums-sdk-support/+page.markdoc
> +- [Docs](https://appwrite.io/docs)
```suggestion
- [Docs](https://appwrite.io/docs/sdks#enums)
```

2024-02-28 07:59 UTC, adityaoberai commented on src/routes/blog/post/introducing-enums-sdk-support/+page.markdoc
> +- [Docs](https://appwrite.io/docs)
Since the enums section would be available here, we can have this link

2024-02-28 08:06 UTC, adityaoberai approved these changes

2024-02-28 11:04 UTC, merged