Announcement messaging
appwrite/website pull request #670
Opened 2024-02-22 14:30 UTC by LauraDuRy

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-02-23 11:12 UTC, eldadfux requested changes

2024-02-23 11:12 UTC, eldadfux commented on src/routes/blog/post/announcing-messaging-set-up-a-messaging-service
> +category: engineering
It should be `product` or something. Engineering needs to be much more technical stuff about our internal processes. We need to have a clear list of categories for the future.

2024-02-23 11:12 UTC, eldadfux commented on src/routes/blog/post/announcing-messaging-set-up-a-messaging-service
> +You can publish announcements and newsletters through topics, deliver user-specific promotions and alerts to all users’ devices, and address individual targets for location-based or real-time alerts.
again devices is not a great word, it usually more common to use it for just push notifications.

2024-02-23 11:12 UTC, eldadfux commented on src/routes/blog/post/announcing-messaging-set-up-a-messaging-service
> +To get started with messaging, you connect a provider, add topics and targets, and send your first message today for your project.
A paragraph about many more adapters to come and call to the community to contribute more could be helpful here.

2024-02-23 11:12 UTC, eldadfux commented on src/routes/blog/post/announcing-messaging-set-up-a-messaging-service
> +Draft, schedule, and send your messages in the Appwrite Console, or use Appwrite SDKs to send messages through code.
I would love a bit more detail about the scheduling feature. Maybe mentioning some example use cases.

2024-02-24 17:27 UTC, adityaoberai commented on src/routes/blog/post/announcing-messaging-set-up-a-messaging-service
> +We will be adding more adopters over time and are open to contributions. Visit our [community page](https://appwrite.io/community) to learn more about contributing or add your issues directly to [Git
```suggestion
We will be adding more adapters over time and are open to contributions. Visit our [community page](https://appwrite.io/community) to learn more about contributing or add your issues directly to [GitHub](https://github.com/appwrite/appwrite/issues).
```

There was a type

2024-02-25 04:21 UTC, gewenyu99 approved these changes

2024-02-25 18:23 UTC, merged