Grammar Fixes #2
appwrite/website pull request #814
Opened 2024-03-22 13:04 UTC by PineappleIOnic

## What does this PR do?

This PR contains various grammar fixes for documentation.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-03-29 16:39 UTC, PineappleIOnic commented on src/routes/docs/products/ai/computer-vision/+page.svelte
> +    <p>
We're splitting history into it's own blog post

2024-03-29 16:40 UTC, PineappleIOnic commented on src/routes/docs/products/ai/computer-vision/+page.svelte
> +    </p>
We're removing all the history stuff away from this page and we are splitting that into a blog post

2024-04-01 19:09 UTC, gewenyu99 requested changes
Reviewed image classification

2024-04-01 19:09 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/object-detection/+page.markdoc
> +```js
I have no idea which file this is.

2024-04-01 19:09 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +{% section #step-7 step=7 title="Create Database" %}
Have this and the storage bucket config in one step call "configure Appwrite"

2024-04-01 19:09 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +Congratulations! You've successfully created an image classification function using Appwrite and Hugging Face.
```suggestion
You've successfully created an image classification function using Appwrite and Hugging Face.
```

2024-04-01 19:09 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +then under the **Events** section click on the **Add Event** button.
```suggestion
Navigate to your function in the Appwrite Console, under **Settings** > **Events**, click on the **Add Event** button.
```

2024-04-01 19:09 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +{% /section %}
It's a little long. Can we combine some of the steps or skip some of them?

2024-04-01 20:04 UTC, gewenyu99 requested changes
@loks0n

2024-04-01 20:04 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/language-translation/+page.markdoc
> +{% section #step-12 step=12 title="Next Steps" %}
step 12?

2024-04-01 22:03 UTC, gewenyu99 submitted a review, later dismissed

2024-04-01 22:03 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +Now we have a collection we're going to add two string attributes to it, `image` and `labels`. The `image` attribute will store the ID of the image we're classifying and the `labels` attribute will s
```suggestion
Add two string attributes to the new collection, `image` and `labels`. The `image` attribute will store the ID of the image we're classifying and the `labels` attribute will store the classification result.
```

2024-04-01 22:03 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +Both of these attributes should be `required` with `image` having the size of `256` and `labels` having the size of around `4096`.
@PineappleIOnic Please use a table to show the attributes more cleanly

2024-04-01 22:03 UTC, gewenyu99 commented on src/routes/docs/products/ai/tutorials/image-classification/+page.markdoc
> +To begin with we're going to add a new function to the `appwrite.js` file we created earlier which will create these records in the database.
```suggestion
To begin, add a new function to the `appwrite.js` file we created earlier which will create these records in the database.
```

2024-04-02 12:43 UTC, PineappleIOnic commented on src/routes/docs/products/ai/tutorials/text-to-speech/+page.markdoc
> +npm install node-fetch node-appwrite
Hugging Face API is borked when it comes to using TTS API's, either results in a timeout or the blob not being parsed correctly

2024-04-06 14:04 UTC, loks0n approved these changes

2024-04-06 14:05 UTC, merged