Ai functions
appwrite/website pull request #973
Opened 2024-05-16 08:22 UTC by LauraDuRy

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-05-16 18:26 UTC, stnguyen90 requested changes

2024-05-16 18:26 UTC, stnguyen90 commented on static/images/blog/function-templates-overview.png
Please move the images in a folder matching the blog (`building-with-ai-function-templates`) so it's organized and we know what blog the image is for.

2024-05-16 18:26 UTC, stnguyen90 commented on src/routes/blog/post/building-with-ai-function-templates/+page.markdoc
> +- [fal.ai](http://fal.aihttps://appwrite.io/docs/products/ai/integrations/fal-ai)
broken link

```suggestion
- [fal.ai](https://appwrite.io/docs/products/ai/integrations/fal-ai)
```

2024-05-17 23:02 UTC, stnguyen90 requested changes
Images still need to be moved.

2024-05-29 07:01 UTC, LauraDuRy commented on static/images/blog/function-templates-overview.png
@adityaoberai can you help me with this? or show me how to do this.

2024-05-30 13:07 UTC, adityaoberai commented
> Images still need to be moved.

@stnguyen90 shifted

2024-06-04 00:10 UTC, stnguyen90 approved these changes

2024-06-04 00:10 UTC, merged